// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Ginz5Qtu-K14HILWwHaqJQC1yqAAM2k',
    appId: '1:271163960914:android:210ed31589c8119760398b',
    messagingSenderId: '271163960914',
    projectId: 'realtimwchat',
    databaseURL: 'https://realtimwchat.firebaseio.com',
    storageBucket: 'realtimwchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLo7j2L_Z9ZyDde8DdPl1DSdhHMlGnjhE',
    appId: '1:271163960914:ios:11d2f693bfdda3a360398b',
    messagingSenderId: '271163960914',
    projectId: 'realtimwchat',
    databaseURL: 'https://realtimwchat.firebaseio.com',
    storageBucket: 'realtimwchat.appspot.com',
    iosClientId:
        '271163960914-lsju4iihf6s3kg2fti2hkg2110b4hgk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.dalel',
  );
}
